version: '3.7'
services:
    apiservice:
        container_name: dropboks
        build:
            context: ./UploadFilesServer
        volumes:
          - C:\TEST\staticFiles:/app/Resources
        ports:
          - "5000:5000"
    uiservice:
        container_name: dropboks_ui
        build:
            context: ./UploadFilesClient
        ports:
          - "4200:4200"
        depends_on:
          - apiservice