version: '3.7'
services:
    apiservice:
        image: matizone/dropboks
        build: https://github.com/MateuszsuetaM/dropboks.git
        volumes:
          - type: bind
            target: /app/Resources
            source: /doker/repos/data
        ports:
          - "5000:80"
    uiservice:
        image: matizone/dropboks_ui
        build: https://github.com/MateuszsuetaM/dropboks_ui.git
        ports:
          - "4200:80"
        depends_on:
          - apiservice